LOOKUP_REQ = '1'
LOOKUP_REP = '2'
JOIN_REQ   = '3'
JOIN_REP   = '4'
LEAVE      = '5'
DISCOVER   = '6'
STOP       = '7'
MOV_DATA_REQ  = '8'
MOV_DATA_REP  = '9'
ACEPT_PRED = '10'
ACEPT_SUC  = '11'
GET_NODES  = '12'
CHECK_REQ  = '13'
CHECK_REP  = '14' 
SET_LEADER = '15'
REP_DATA_REQ = '16'
REP_DATA_REP = '17'
SET_DATA_REQ = '18'
SET_DATA_REP = '19'
SET_REP_DATA_REQ = '20'
GET_DATA_REQ  = '21'
GET_DATA_REP  = '22'
SET_NODES = '23'

#Creates and Updates
CREATE_PROFILE = '30'
REP_PROFILE = '31'
CREATE_GROUP = '32'
REP_GROUP = '33'
CREATE_PEVENT = '34'  # ESTE LO AGREGUE
REP_EVENT = '35'
CREATE_GEVENT = '36'  # ESTE LO AGREGUE


ACEPT_EVENT = '40'  # ESTE LO AGREGUE
DECLINE_EVENT = '41'  # ESTE LO AGREGUE

#delete
# DELETE_PROFILE = '50'
# DELETE_GROUP = '51'
DELETE_EVENT = '52'
DELETE_NOTIFICATION = '54'  # ESTE LO AGREGUE


#Queries
GET_PROFILE = '60'
GET_NOTIFICATIONS = '61' # ESTE LO AGREGUE
GET_EVENTS = '62' # ESTE LO AGREGUE
GET_HIERARCHICAL_MEMBERS = '63' # ESTE LO AGREGUE
GET_EVENTS_MEMBER = '64' # ESTE LO AGREGUE
SHOW_MSGS = '65'